POST http://localhost:7406/meter-service/lora-params
Content-Type: application/json;charset=UTF-8
Accept: application/json
Cache-Control: no-cache

{
	"companyCode": "amwares",
	"devEui": "1111110000001245"
}

###

