POST http://localhost:7406/serial-port/
Content-Type: application/json;charset=UTF-8
Accept: application/json
Cache-Control: no-cache

{
	"name": "COM6",
	"active": true,
	"baudRate": 2400,
	"dataBits": 8,
	"stopBits": 1,
	"parity": 2
}

###

